# These are supported funding model platforms
github: [automotiv]                    # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: "khetisahayak"                   # Replace with a single Patreon username
open_collective: "prakash-ponali"           # Replace with a single Open Collective username
ko_fi: "prakashponali"                     # Replace with a single Ko-fi username
tidelift: ""                  # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
liberapay: "prakashponali"                 # Replace with a single Liberapay username
issuehunt: "Prakash Ponali"                 # Replace with a single IssueHunt username
lfx_crowdfunding: ""          # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: "khetisahayak"                     # Replace with a single Polar username
buy_me_a_coffee: "prakashponali"           # Replace with a single Buy Me a Coffee username
thanks_dev: "gh/automotiv"                # Replace with a single thanks.dev username
custom: []                     # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
