# These are supported funding model platforms

github: [automotiv]
patreon: # Add Patreon username if applicable
open_collective: # Add Open Collective username if applicable
ko_fi: # Add Ko-fi username if applicable
custom: ['https://khetisahayak.com/donate', 'https://github.com/sponsors/automotiv']
