# Kheti Sahayak - CodeRabbit Configuration
# Agricultural Platform Code Quality Standards

# Project metadata
project:
  name: "Kheti Sahayak"
  description: "Digital Agricultural Platform for Indian Farmers"
  language: "java"
  framework: "spring-boot"
  domain: "agricultural"

# Code quality focus areas
focus:
  - "security"
  - "performance"
  - "accessibility"
  - "agricultural-domain"
  - "rural-connectivity"
  - "farmer-data-protection"

# Agricultural domain-specific rules
agricultural_rules:
  crop_validation:
    - "Validate crop types against Indian agricultural standards"
    - "Ensure seasonal logic for Kharif/Rabi/Zaid cropping patterns"
    - "Include regional variations for different Indian states"
  
  weather_integration:
    - "Validate weather data accuracy and sources"
    - "Implement proper error handling for weather API failures"
    - "Ensure hyperlocal weather data for farming decisions"
  
  farmer_privacy:
    - "Protect farmer location data with proper anonymization"
    - "Implement secure data handling for sensitive agricultural information"
    - "Ensure GDPR compliance for farmer data"

# Security requirements
security:
  input_validation:
    - "All API endpoints must validate inputs"
    - "Implement proper sanitization for agricultural data"
    - "Prevent SQL injection and XSS attacks"
  
  authentication:
    - "JWT token validation for all protected endpoints"
    - "Role-based access control for farmers, experts, and admins"
    - "Secure password handling and OTP verification"

# Performance optimization for rural networks
performance:
  rural_optimization:
    - "Image compression for crop diagnosis uploads"
    - "Offline support for critical farming features"
    - "Optimize for 2G/3G network conditions"
    - "Implement caching for frequently accessed data"
  
  mobile_optimization:
    - "Bundle size optimization for mobile devices"
    - "Progressive loading for agricultural content"
    - "Efficient data synchronization"

# Accessibility compliance
accessibility:
  wcag_compliance:
    - "WCAG 2.1 AA compliance for inclusive design"
    - "Screen reader support for visually impaired farmers"
    - "Keyboard navigation for all interactive elements"
    - "Multi-language support for regional farmers"

# Code quality gates
quality_gates:
  security_score: 9  # High security for farmer data
  performance_score: 8  # Optimized for rural networks
  accessibility_score: 9  # WCAG 2.1 AA compliance
  maintainability: 8  # Clean, readable code
  agricultural_accuracy: 9  # Domain-specific correctness

# File patterns to analyze
include_patterns:
  - "**/*.java"
  - "**/*.ts"
  - "**/*.tsx"
  - "**/*.js"
  - "**/*.jsx"

# Exclude patterns
exclude_patterns:
  - "**/node_modules/**"
  - "**/target/**"
  - "**/build/**"
  - "**/.git/**"
  - "**/coverage/**"

# Custom rules for agricultural platform
custom_rules:
  - name: "crop_data_validation"
    pattern: "CropData|CropType|Season"
    message: "Ensure crop data validation against Indian agricultural standards"
    severity: "high"
  
  - name: "farmer_privacy_protection"
    pattern: "location|coordinates|gps"
    message: "Protect farmer location data with proper anonymization"
    severity: "critical"
  
  - name: "weather_data_security"
    pattern: "weather|forecast|climate"
    message: "Implement secure weather data handling"
    severity: "high"
  
  - name: "mobile_optimization"
    pattern: "image|upload|file"
    message: "Optimize for mobile and rural connectivity"
    severity: "medium"