import 'dart:typed_data';
import 'package:kheti_sahayak_app/models/scheme.dart';
import 'package:kheti_sahayak_app/models/user.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class DocumentChecklistService {
  // Mock data for required documents if not present in scheme
  static List<String> getChecklistForScheme(Scheme scheme) {
    if (scheme.requiredDocuments.isNotEmpty) {
      return scheme.requiredDocuments;
    }

    // Fallback mock data based on scheme name or category
    if (scheme.name.toLowerCase().contains('kisan')) {
      return [
        'Aadhar Card',
        'Bank Passbook Copy',
        'Land Record (7/12 Extract)',
        'Passport Size Photo',
      ];
    } else if (scheme.name.toLowerCase().contains('soil')) {
      return [
        'Soil Sample Details',
        'Aadhar Card',
        'Farm Map',
      ];
    } else {
      return [
        'Aadhar Card',
        'Identity Proof',
        'Address Proof',
        'Income Certificate',
      ];
    }
  }

  static Map<String, String> getAutoFilledData(User user) {
    return {
      'Full Name': user.fullName ?? '',
      'Mobile Number': user.phoneNumber ?? '',
      'Address': user.address ?? '',
      'Email': user.email,
    };
  }

  static Future<void> generateChecklistPdf(
    Scheme scheme,
    User user,
    Map<String, bool> checkedItems,
  ) async {
    final pdf = pw.Document();
    final checklist = getChecklistForScheme(scheme);
    final userData = getAutoFilledData(user);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('Document Checklist: ${scheme.name}',
                    style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Applicant Details:',
                  style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              ...userData.entries.map((entry) {
                return pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 5),
                  child: pw.Row(
                    children: [
                      pw.Text('${entry.key}: ',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text(entry.value),
                    ],
                  ),
                );
              }).toList(),
              pw.SizedBox(height: 20),
              pw.Text('Required Documents:',
                  style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              ...checklist.map((item) {
                final isChecked = checkedItems[item] ?? false;
                return pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 10),
                  child: pw.Row(
                    children: [
                      pw.Container(
                        width: 12,
                        height: 12,
                        decoration: pw.BoxDecoration(
                          border: pw.Border.all(),
                          color: isChecked ? PdfColors.black : null,
                        ),
                      ),
                      pw.SizedBox(width: 10),
                      pw.Text(item),
                      if (isChecked)
                        pw.Padding(
                          padding: const pw.EdgeInsets.only(left: 10),
                          child: pw.Text('(Collected)',
                              style: const pw.TextStyle(color: PdfColors.green)),
                        ),
                    ],
                  ),
                );
              }).toList(),
              pw.SizedBox(height: 40),
              pw.Divider(),
              pw.Text(
                'Generated by Kheti Sahayak App',
                style: const pw.TextStyle(color: PdfColors.grey),
              ),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'Checklist_${scheme.name.replaceAll(' ', '_')}.pdf',
    );
  }
}
