# This workflow deploys the application to the PRODUCTION environment on AWS Elastic Beanstalk.
# It is triggered only on a push to the 'main' branch.

name: Deploy to Production

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Define a 'production' environment in repo settings for protection rules

    steps:
      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # <-- TODO: Change to your production AWS region

      # Step 2: Generate Dockerrun.aws.json for the specific commit
      # This uses the unique Git SHA to ensure we deploy the exact version that was tested.
      - name: Generate Dockerrun.aws.json
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ secrets.DOCKERHUB_USERNAME }}/kheti-sahayak-backend:${{ github.sha }}",
              "Update": "true"
            },
            "Ports": [
              { "ContainerPort": 3000 }
            ]
          }' > Dockerrun.aws.json

      # Step 3: Deploy to the Production Elastic Beanstalk Environment
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: kheti-sahayak-backend # <-- Should be the same as staging
          environment_name: kheti-sahayak-production # <-- IMPORTANT: Use the production environment name
          region: us-east-1 # <-- TODO: Change to your production AWS region
          version_label: prod-${{ github.sha }}
          deployment_package: Dockerrun.aws.json
          tags: "Project=kheti-sahayak,Environment=production"
          wait_for_environment_recovery: 600 # Wait up to 10 minutes for the deployment to complete